### ISSUE TITLE
Hide VNC config window

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#106]
This window is popping up on neurodesk play and most people click it away as their first action:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/4021595/182946939-dc75e3c4-b058-4dc1-b2d4-648b66131002.png">

Any ideas how to remove it?

**Comment by aswinnarayanan** [comment]
Found the solution. Will push this through

**Comment by stebo85** [comment]
oh wow, cool :)

**Comment by aswinnarayanan** [comment]
Fixed for neurodesk play

**Comment by stebo85** [comment]
awesome :) That is beautiful! I think you saved multiple 100 people per month from closing this stupid window :D
