### ISSUE TITLE
Neurodesk Docker Container Missing Software

### ISSUE THREAD

**Issue by JMmedphys** [NeuroDesk/neurodesktop#108]
Hi I followed the instructions in https://www.neurodesk.org/docs/neurodesktop/getting-started/linux/ to setting up neurodesk and I can get it running through docker. I have also ensured that neurodesktop-storage has all read and write permissions.

When I load into neurodesktop, using pip list indicates that nipype is not installed. 

In addition, I have tried pip install nipype[all], run spm12 r7771 once and in a separate terminal "ml spm12/r7771". After which I ran 

from nipype.interfaces import spm
matlab_cmd = '/opt/spm12/run_spm12.sh /opt/mcr/v97/ script'
spm.SPMCommand.set_mlab_paths(matlab_cmd=matlab_cmd, use_mcr=True)

print(spm.SPMCommand().version)
which returns none .

I have also repeated the same steps with older neurodesk images but I run into the same problem. Would appreciate some advice in what I might be doing wrong in getting started. Thank you!

OS:
Ubuntu 20.04 LTS

Host Terminal output:
sudo docker run \
  --shm-size=1gb -it --privileged --name neurodesktop \
  -v ~/neurodesktop-storage:/neurodesktop-storage \
  -e HOST_UID="$(id -u)" -e HOST_GID="$(id -g)"\
  -p 8080:8080 \
  -h neurodesktop-20220813 vnmd/neurodesktop:20220813

==================================================================
Starting SSH server
 * Restarting OpenBSD Secure Shell server sshd                           [ OK ] 
==================================================================
Starting RDP server
 * Restarting Remote Desktop Protocol server                                    xrdp-sesman[56]: (56)(140051190646336)[DEBUG] libscp initialized

xrdp-sesman[56]: (56)(140051190646336)[DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 port 3350.

xrdp-sesman[56]: (56)(140051190646336)[DEBUG] Closed socket 4 (AF_INET6 ::ffff:127.0.0.1 port 3350)

xrdp-sesman[57]: (57)(140051190646336)[INFO ] starting xrdp-sesman with pid 57

xrdp-sesman[57]: (57)(140051190646336)[INFO ] listening to port 3350 on 127.0.0.1

                                                                         [ OK ]
Setting UID to 1000
usermod: no changes
Setting GID to 1000
    ==================================================================
    Mounting CVMFS
CernVM-FS: running with credentials 109:115
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/neurodesk.ardc.edu.au
    ==================================================================
    Testing which CVMFS server is fastest
OK
  [0] http://cvmfs-ashburn.neurodesk.org/cvmfs/neurodesk.ardc.edu.au (50 ms)
  [1] http://cvmfs.neurodesk.org/cvmfs/neurodesk.ardc.edu.au (55 ms)
  [2] http://cvmfs-zurich.neurodesk.org/cvmfs/neurodesk.ardc.edu.au (154 ms)
  [3] http://cvmfs-sydney.neurodesk.org/cvmfs/neurodesk.ardc.edu.au (205 ms)
  [4] http://cvmfs-perth.neurodesk.org/cvmfs/neurodesk.ardc.edu.au (351 ms)
Active host 0: http://cvmfs-ashburn.neurodesk.org/cvmfs/neurodesk.ardc.edu.au
==================================================================
Starting tomcat server
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:   -Xms512M -Xmx1024M
Tomcat started.
==================================================================
Starting Guacamole Daemon
------------------------------------------------------------------
    Use this link for direct Neurodesktop:
!!! http://localhost:8080/#/?username=user&password=password !!!
    Once connected to the session, your user info is:
    Username: "user"
    Password: "password"
------------------------------------------------------------------
guacd[199]: INFO:	Guacamole proxy daemon (guacd) version 1.4.0 started
guacd[199]: INFO:	Listening on host 127.0.0.1, port 4822

**Comment by stebo85** [comment]
Dear @JMmedphys,

You did everything right and the problem is that we haven't finished the integration of nipype. However, if you are happy to provide feedback there isn't much missing and we hopefully get it to work nicely in a few days :)

what you ran is correct, but it only works when you open spm through the application menu and since we had not yet finished the nipype integration Python is not on the path:

Can you let me know if this works for you?
1) open spm12 from the application menu
```
PATH=$PATH:/opt/miniconda-latest/bin/
python
from nipype.interfaces import spm
matlab_cmd = '/opt/spm12/run_spm12.sh /opt/mcr/v97/ script'
spm.SPMCommand.set_mlab_paths(matlab_cmd=matlab_cmd, use_mcr=True)

print(spm.SPMCommand().version)
```
<img width="531" alt="image" src="https://user-images.githubusercontent.com/4021595/185782455-4529f751-5ab9-453b-bb72-a2f3ed9bd696.png">

if that works for you, I can extend this to enable other toolkits as well. Which tools are you aiming to combine in a nipype workflow?

**Comment by JMmedphys** [comment]
Dear @stebo85 

Thank you for the reply! I see, glad to know I did not mess up somewhere.

I can confirm that what you suggested works when I run spm through the application menu. 

print(spm.SPMCommand().version) returns 12.7771 .

I intend to combine SPM, AFNI and FSL within a nipype workflow. 

Thank you so much for your time and attention.

**Comment by stebo85** [comment]
Dear @JMmedphys,

I finished a first version of Nipype in Neurodesk. Could you test neurodesktop version "20220825" and let me know if everything works as expected?

You find nipype under Applications -> workflows

You can find the instruction here and it's also output inside the container:
https://github.com/NeuroDesk/neurocontainers/tree/master/recipes/nipype

I also noticed that you had a quite high latency to our cvmfs servers, with the fastest server being in US east and 50ms latency:
[0] http://cvmfs-ashburn.neurodesk.org/cvmfs/neurodesk.ardc.edu.au (50 ms)

I now added another server in US west - hoping that this is where you are roughly located and that applications startup a lot faster for you now :)

Thank you
Steffen

**Comment by JMmedphys** [comment]
Dear @stebo85 

Thank you for the update and for setting up another server! I followed the instruction in the link you provided but I think the python package is missing.

Thank you for your attention to this issue.
![Screenshot 2022-08-25 195326](https://user-images.githubusercontent.com/105614591/186795437-d2fd2b82-aefc-4fe0-ad94-eaa8ddb68577.png)

**Comment by stebo85** [comment]
Dear @JMmedphys,

Thank you for trying it so quickly :) 

You need to start the nipype container from the application menu -> workflows -> nipype

you could also try to use module load in the general terminal ('ml nipype'), but I haven't tested that yet :p

Can you let me know if that works?

**Comment by JMmedphys** [comment]
Dear @stebo85 

So I have been trying to run the code but I keep coming across permission denied, which is weird because I am running the neurodesktop container with sudo and --privileged flag. What I tried this time was to start the nipype container from the application menu and follow the instructions in the link.

For the setup steps: I switched to another terminal and used sudo to run the wget and gunzip lines. Otherwise I would have encountered permission denied errors. 

Trying to run the spm part of the python code gives the error in the image below.

I realised I forgot to mention in my earlier reply than I am now using WSL2 with ubuntu 20.04 and running docker (not docker desktop) through WSL2.

===
sudo docker run \
  --shm-size=1gb -it --privileged --name neurodesktop \
  -v ~/neurodesktop-storage:/neurodesktop-storage \
  -e HOST_UID="$(id -u)" -e HOST_GID="$(id -g)" \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e NVIDIA_DISABLE_REQUIRE=1 \
  -p 8080:8080 -h neurodesktop-20220825 \
  vnmd/neurodesktop:20220825

![image](https://user-images.githubusercontent.com/105614591/186996835-7dd07cac-07aa-4c14-9d18-b586bfb2e0bd.png)

**Comment by stebo85** [comment]
Dear @JMmedphys 

You need to make the neurodesktop-storage folder writable before starting the docker container as described in the Linux instructions:

chmod a+rwx ~/neurodesktop-storage

**Comment by JMmedphys** [comment]
Dear @stebo85 

Thank you for your patience.

I did do chmod command originally. I fear this an issue with using docker through wsl2 instead of docker desktop on windows. I will be setting up an ubuntu20.04 virtual machine to attempt again. Will update.

**Comment by stebo85** [comment]
Dear @JMmedphys,

It shouldn't be a problem of WSL - I run it the same way.

Can you check the permissions of the neurodesktop-storage folder in WSL?

**Comment by JMmedphys** [comment]
Dear @stebo85 

Please see attached.

![image](https://user-images.githubusercontent.com/105614591/187010591-1af8283d-d63c-44aa-ba67-925d58a1c3ff.png)

**Comment by stebo85** [comment]
@JMmedphys,

ok, great. Now open neurodesktop in the browser and check if you can create files inside /neurodesktop-storage

**Comment by JMmedphys** [comment]
Dear @stebo85 

This is the result:

![image](https://user-images.githubusercontent.com/105614591/187010894-e5b011dc-8ab0-43ff-8dd0-d4d5434ac327.png)

**Comment by stebo85** [comment]
hm, that's strange. Did you stop the container before changing permissions?

If you like to quickly debug this interactively: https://uqz.zoom.us/j/84115698774

**Comment by stebo85** [comment]
ok, problem solved - and for completeness the solution here: There were two different neurodesktop-storage folders and one had the wrong permission set.

**Comment by JMmedphys** [comment]
@stebo85 Thank you so much for your patience and attention on this matter. Just wanted also follow up and add that I had no issues with https://github.com/NeuroDesk/neurocontainers/tree/master/recipes/nipype 

Thank you so much once again!

**Comment by stebo85** [comment]
Wonderful to hear:)
