### ISSUE TITLE
MatlabGUI license issue

### ISSUE THREAD

**Issue by JonteP** [NeuroDesk/neurodesktop#111]
I tried running the Matlab GUI and entered my account details. I got the following error:

![matlab_error](https://user-images.githubusercontent.com/40265580/191768387-1d501b67-d003-4d81-a7b1-82fecc0a4993.png)

**Comment by stebo85** [comment]
Dear @JonteP,

Yes, that's unfortunately another bug and we haven't found a good way of solving this - but @civier is working on it. The workaround is to download a license file from matlab and place it in your Downloads folder inside Neurodesk. Then matlab starts with this license.

Here is the help document describing the problem
https://github.com/NeuroDesk/neurocontainers/tree/master/recipes/matlab

**Comment by JonteP** [comment]
Thank you @stebo85! 
I tried searching for the issue before posting, but somehow failed to find that readme. Sorry for the redundant bug report.
I also found the discussion section at NeuroDesk/neurodesk.github.io so I will be sure to check there first in the future.

**Comment by stebo85** [comment]
No worries @JonteP - we didn't document this problem yet because we were hoping to find a quick solution.

**Comment by stebo85** [comment]
fixed and working in all releases
