### ISSUE TITLE
Some specific keys are not transmitted into NeuroDesktop

### ISSUE THREAD

**Issue by korbinian90** [NeuroDesk/neurodesktop#112]
The pipe symbol cannot be written in Neurodesktop (shell and matlab GUI): |
Also backslash: \

**Comment by stebo85** [comment]
oh, interesting. That works for me - which keyboard layout is that? Which browser?

**Comment by stebo85** [comment]
So, we narrowed the problem down to the german keyboard layout and that ALT-GR is grabbed by linux.

**Comment by stebo85** [comment]
@korbinian90,

can you try the following: 
sudo dpkg-reconfigure keyboard-configuration 


then the following settings:
Keyboard model: 72
Country of origin for the keyboard: 25
Key to function as AltGr: 3
Compose key: 1
Use Control+Alt+Backspace to terminate the X server? [yes/no] no

**Comment by korbinian90** [comment]
/etc/default/keyboard

**Comment by korbinian90** [comment]
File changed, but it seems to not do anything.
Do I have to restart anything for it to work?
I tried to reopen the console

**Comment by stebo85** [comment]
ok, i build it in the docker image then and we can test it that way :)

**Comment by stebo85** [comment]
@korbinian90 can you test this version?

neurodesktop:20221116

**Comment by korbinian90** [comment]
Further test:
The behaviour is identical on neurodesktop:20220813 and neurodesktop:20221116

Whenever one "[" key is type (which doesn't appear) the next altGr key typed afterwards appears.

**Comment by stebo85** [comment]
Dear @korbinian90 

I now documented the workarounds: https://www.neurodesk.org/docs/neurodesktop/troubleshooting/#i-am-using-a-european-keyboard-layout-and-i-cannot-type-symbols-that-require-the-alt-gr-key-like--or-

Can you test them and let me know if they do not work for you? I am closing this issue for now, but feel free to reopen if it's not solved :)

Thank you
Steffen
