### ISSUE TITLE
neurodesktop app list unresponsive on cvl

### ISSUE THREAD

**Issue by kel-github** [NeuroDesk/neurodesktop#115]
Hey folks,

I am using neurodesktop on the cvl on wiener. I am remote from UQ at the moment, connected to the VPN via cisco anyconnect.

The neurodeskt applications menu is unresponsive; I am unable to select any of the neurodesk - for example if I go to 'neuroimaging tools' > 'neurodesktop' > 'functional imaging' > fmriprep and click, nothing happens, but if I go 'neuroimaging tools' > 'afni' then the terminal window opens fine.

Just wondering if this could be a neurodesk specific issue? 
Any info much appreciated :)

**Comment by stebo85** [comment]
Dear @kel-github,

It's all working for me unfortunately, so I am suspecting a connectivity issue from your side. 

Can you try to login via:
https://desktop.cvl.org.au/ 

and check if the problem is there as well?

Thank you
Steffen

**Comment by aswinnarayanan** [comment]
Hi @kel-github, are you able to run /scratch/cvl-admin/neurodesk/local/bin/fmriprep-21_0_1.sh from a terminal?

**Comment by stebo85** [comment]
you can try the alternative login - that would exclude issues with fastx

**Comment by aswinnarayanan** [comment]
I'm having trouble with accessing the cvl desktop currently. Will get back if I find something

**Comment by kel-github** [comment]
Thanks Aswin :)
