### ISSUE TITLE
Add decision tree for new users 

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurodesktop#119]
Suggest including feature on the website for new users:

'New to neurodesk? Click here'
Then have a decision tree for where to compute with the following:

> Are you an Australian Researcher (AAF)
> Do you want to compute on your local computer or on the cloud > Linux, Mac, Windows
> Do you need persistent file storage? 

Then provide the setup instructions for each - would be beneficial for new users who aren't sure what flavour of neurodesk to choose. :)

**Comment by stebo85** [comment]
idea: use https://pytorch.org/ decision table

**Comment by stebo85** [comment]
@iishiishii

**Comment by iishiishii** [comment]
I'm on this issue.

**Comment by iishiishii** [comment]
![neurodesk](https://user-images.githubusercontent.com/59903692/210670748-711b4f59-7f37-4320-b156-64b3d248eb66.gif)

Let me know if you have more suggestions to this

**Comment by thomshaw92** [comment]
Looks great! That is very cool 👍 
Are the links at the bottom clickable? 

At the risk of over-engineering: I think 'Your OS' would be better below 'compute platform', and only available if "CPU" was selected.

Is there a better word for 'CPU'? Like 'Local' or 'Personal Computer'?

**Comment by aswinnarayanan** [comment]
@iishiishii this looks amazing!!!

For cpu, either PC or Desktop/Laptop could work.

**Comment by stebo85** [comment]
Wow, that's very cool! That should make the wide variety of execution options nicely visible and managable :) 

Now we just need to think a little bit more about how to structure it. I agree with Tom that CPU is not so helpful - also we should pre-think that we can also support GPUs. 

Can you control the output of every combination?

From my perspective we have the following execution options:


1) Local x86 Docker Desktop Container running on Windows 
2) Local x86 Docker Desktop Container running on MacOS
3) Local x86 Docker Desktop Container running on Linux + GPU support possible
4) Cloud x86 Docker Desktop Container running on Linux + GPU support possible (-> SSH tunnel to cloud vm)

5) Cloud Kubernetes x86 Jupyter hub (with persistent home directory) + GPU support possible 
6) Cloud Kubernetes x86 Binder hub (no persistent home directory)

7) Neurocommand on HPC running Linux -> GUI via x11, GPU support possible
8) Neurocommand on Linux -> GUI via x11, GPU support possible
9) Neurocommand on WSL -> GUI via x11 
10) CVMFS in Jupyter -> google colab, GPU support possible
11) CVMFS in Linux, GPU support possible
12) CVMFS in WSL for Windows

13) Nectar

Now the questions is how to categorize this?
I think the big choices are:
a) Local Install vs HPC vs Cloud vs Managed
b) Windows vs Mac vs Linux 
c) Full Desktop vs Command Line vs CVMFS
d) GPU support or not
e) ARM vs x86 (Future option)

Currently it's all x86, future options would add an ARM version to all of this, so we would end up with 26 variants

Should we simplify these options more?

**Comment by iishiishii** [comment]
Thanks for all the feedbacks! 
The link is clickable, I changed the color when hovering over so it's more noticeable.
It indeed makes more sense to have Platform above OS.
I set x86, ARM and GPU as Processor category for now, we can change that when there's more update for ARM and GPU.
The command is changed by the combination of categories eg. `x86,gui,linux,local,aus` . 
I tried to cross out option that's unavailable for certain category and toggle to suitable option, let me know if you think it's useful or confusing.

![neurodesk_install](https://user-images.githubusercontent.com/59903692/211225824-abbca2ba-c27f-49c0-baf4-294bfdef01f5.gif)

**Comment by stebo85** [comment]
That's perfect @iishiishii :)

**Comment by iishiishii** [comment]
Great, I made it ready for review and merging.

**Comment by thomshaw92** [comment]
@iishiishii When clicking on the link at the bottom of the windows local install, it sends me to the Mac instructions.

**Comment by stebo85** [comment]
Good find Tom! The link looks correct, so I didn't find it when checking

**Comment by iishiishii** [comment]
Wow thanks for testing it! I'll updated them.

**Comment by iishiishii** [comment]
![image](https://user-images.githubusercontent.com/59903692/213324780-99b122b2-dd8b-4df0-a79d-5b6b74e65983.png)

Some more updates on the landing page. I don't see any nice featuring screenshot for the components. Maybe I'll just exclude them?

**Comment by stebo85** [comment]
Dear @iishiishii - that looks good. I hope you can get the background transparent or black for the Neurocontainers image.
