### ISSUE TITLE
Fix redirect with HPC option on neurodesk.org

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurodesktop#120]
Clicking on HPC option on homepage should redirect to Linux options straight away? Or be its own page

**Comment by stebo85** [comment]
change current HPC site to get stuff from neurocommand linux

**Comment by thomshaw92** [comment]
https://github.com/NeuroDesk/neurodesk.github.io/pull/216 closed

**Comment by thomshaw92** [comment]
https://github.com/NeuroDesk/neurodesk.github.io/pull/216
