### ISSUE TITLE
clipboard is broken when copying special characters

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#124]
When copying anything with special characters the clipboard breaks and it cannot be pasted. This happens in VNC and RDP. Here is an example:

![Image](https://user-images.githubusercontent.com/4021595/208342170-bf25bb2f-33a3-4525-8758-2296d1ac2bfb.png)

It works on Nectar virtual desktop - so it could be a bug in our guacamole version

This issue was identified by @civier

**Comment by aswinnarayanan** [comment]
@stebo85 @civier Can I confirm, is this happening on RDP?
I'm able to replicate this on VNC. 
But RDP and Nectar VDS are working for me

**Comment by stebo85** [comment]
So, I tested a bit more. Interestingly, it works now for me on Jupyterhub with VNC. I tested this special character: "dürfen" - but it seems to be long dashes and special quotation marks as well based on Oren's observation. Interestingly, I can paste for example in vscode and then it comes up with this: "dü?rfen" - weird problem - we need more data to understand this I think.

**Comment by civier** [comment]
Hi Steffen. I saw you assigned me this issue. Can you explain what you want
me to do?

**Comment by stebo85** [comment]
@civier - it would be great to get more information about this problem. Since you reported it first I thought you could add more details. Once we understand it better, we can find a good solution.

**Comment by stebo85** [comment]
try and see what happens with latest guacamole version
