### ISSUE TITLE
Exporting locally defined variables into ML software

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurodesktop#129]
A colleague is running recon-all as part of a pipeline on Nectar

They ran into issues exporting the SUBJECTS_DIR variable into their code, which was written as a script. 

I suggested opening the freesurfer terminal from the neurodesk, but this isn't ideal - have we implemented something to export locally defined variables into the container?

**Comment by stebo85** [comment]
The Readme explains how to do this: 
https://github.com/NeuroDesk/neurocontainers/tree/master/recipes/freesurfer

export SUBJECTS_DIR=/neurodesktop-storage/freesurfer_output
export SINGULARITYENV_SUBJECTS_DIR=$SUBJECTS_DIR

Should we state this more clearly in the FAQ section or anywhere else :?

**Comment by thomshaw92** [comment]
Can we childproof it somehow ? I think this was a goal at some point - that we somehow list all user defined exported variables to singularityenv? 
Maybe for the next hack :)

**Comment by thomshaw92** [comment]
Perhaps dynamically exporting the env to singularityenv whenever a container binary is invoked?

**Comment by stebo85** [comment]
Dear @thomshaw92 

We can "simply" unset the variable inside the container and then it will be overwritten and one doesn't need to use SINGULARITY_ENV. The downside is that then one HAS to set it - otherwise it will not work.

We therefore decided to give this variable a sensible default inside the container and overwrite it in the different employments.

**Comment by stebo85** [comment]
Dear @thomshaw92 ,

I now added this line to all .bashrcs of neurodesk:
export SINGULARITYENV_SUBJECTS_DIR=~/freesurfer-subjects-dir

Once this pull request here is merged, it will also be on nectar VDI :)
https://github.com/NeCTAR-RC/bumblebee-images/pull/7

Could you test if that works?

Thank you
Steffen

**Comment by stebo85** [comment]
Dear @thomshaw92 

The pull request is merged and I just tested it on Nectar VDI and it's working perfectly :)

Thank you for flagging this usability improvement.

Cheers
Steffen
