### ISSUE TITLE
Update mriqc?

### ISSUE THREAD

**Issue by PatricioSolis-Urra** [NeuroDesk/neurodesktop#130]
Hello,

I'm currently using MRIQC on neurodesk, following this tutorial: https://www.neurodesk.org/tutorials/functional_imaging/mriqc_cvl/. Recently, I tested the same MRI image on both Neurodesk and my local machine and noticed that the quality metrics obtained were different. While there could be differences due to the operating system, the Neurodesk MRQC generated a warning message: "You are using MRIQC v0.16.1, and a newer version is available: 22.0.6."

I would like to ask if anyone knows whether it's possible to update MRIQC to the latest version, and if so, how to do it. I'm hoping this will help address the discrepancies in the quality metrics.

Thank you in advance for your help.

Best regards,
Patricio

**Comment by stebo85** [comment]
Dear @PatricioSolis-Urra,

Yes, matching the version for MRIQC could be important if you want the same results :)

I updated MRIQC to 22.0.6 in Neurodesk. 

How are you accessing Neurodesk? The cloud versions are already updated, the desktop version will include the new tool in a few hours.

Thank you
Steffen

**Comment by PatricioSolis-Urra** [comment]
Great! 
Thank you very much for your help, @stebo85. 
I am using the desktop version. 
I will wait for the updates 
Best regards,
Patricio

**Comment by stebo85** [comment]
Dear @PatricioSolis-Urra,

Wonderful - can you try the neurodekstop version: vnmd/neurodesktop:20230216

let me know if this works :)

Cheers
Steffen

**Comment by stebo85** [comment]
Dear @PatricioSolis-Urra,

Just checking if this is all working for you now and I can close the issue?

Thank you
Steffen

**Comment by PatricioSolis-Urra** [comment]
Dear @stebo85,
Yes, all is working for me. Thanks a lot for the quick response.
best,
Patricio
