### ISSUE TITLE
Update background for dark mode

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurodesktop#133]
@stebo85, what do you think about switching to the nectar desktop background in the upcoming, for better dark mode support.

![background](https://user-images.githubusercontent.com/25297584/220275313-90c95b7f-e31e-4f32-9843-127ed3f9f987.svg)

**Comment by stebo85** [comment]
yes, great idea :) also increases consistency across systems!

**Comment by aswinnarayanan** [comment]
Sounds good. I'll use it with the jupyter update

**Comment by aswinnarayanan** [comment]
Completed #147
