### ISSUE TITLE
Fail to run latest neurodesktop (20220524)

### ISSUE THREAD

**Issue by JonteP** [NeuroDesk/neurodesktop#152]
I try to run the docker image with this command:
`docker run --mac-address 02:42:ac:11:00:02 --rm --shm-size=4gb -it --privileged --name neurodesktop -v [my_volume] -v [my_local_folder]:/neurodesktop-storage/local -p 8080:8080 -h neurodesktop-20230524 vnmd/neurodesktop:20230524`

and get this:

Entered start.sh with args: jupyter lab
/usr/local/bin/start.sh: running hooks in /usr/local/bin/start-notebook.d as uid / gid: 1000 / 100
/usr/local/bin/start.sh: running script /usr/local/bin/start-notebook.d/start-notebook.sh
/usr/local/bin/start.sh: done running hooks in /usr/local/bin/start-notebook.d
WARNING: container must be started as root to grant sudo permissions!
/usr/local/bin/start.sh: running hooks in /usr/local/bin/before-notebook.d as uid / gid: 1000 / 100
/usr/local/bin/start.sh: running script /usr/local/bin/before-notebook.d/before-notebook.sh
Changing password for jovyan.
Current password: New password: Retype new password: Password change has been aborted.
passwd: Authentication token manipulation error
passwd: password unchanged

I then tried to add  **-u root**  to the docker command. I then get stuck on:

Ensuring /home/jovyan is owned by 1000:100 (chown options: -R)

This seems to be related to Jupyter lab?

**Comment by stebo85** [comment]
dear @JonteP,

the image version you try to open is not released yet. we re-developed the image from scratch and the startup command needs to be updated to:

docker run --shm-size=1gb -it --cap-add SYS_ADMIN --security-opt apparmor:unconfined     --device=/dev/fuse --name neurodesktop -v ~/neurodesktop-storage:/neurodesktop-storage     -p 8888:8888     --user=root -e NB_UID="$(id -u)" -e NB_GID="$(id -g)" vnmd/neurodesktop:xxxxxxx

we will update the website and make a new big release in the next days - we just need a little more testing. but you are welcome to help testing :)

**Comment by JonteP** [comment]
> dear @JonteP,
> 
> the image version you try to open is not released yet. we re-developed the image from scratch and the startup command needs to be updated to:
> 
> docker run --shm-size=1gb -it --cap-add SYS_ADMIN --security-opt apparmor:unconfined --device=/dev/fuse --name neurodesktop -v ~/neurodesktop-storage:/neurodesktop-storage -p 8888:8888 --user=root -e NB_UID="$(id -u)" -e NB_GID="$(id -g)" vnmd/neurodesktop:xxxxxxx
> 
> we will update the website and make a new big release in the next days - we just need a little more testing. but you are welcome to help testing :)

I see. I just assumed anything I found at dockerhub was released. :)

But thank you for the updated startup command!

**Comment by JonteP** [comment]
Unfortunately, all I get is " invalid group ID '$(id -g)' "

**Comment by stebo85** [comment]
Ahh, are you running this in windows? Try WSL or wait a few days until the windows command is ready and tested

**Comment by stebo85** [comment]
On windows, this should work (not tested): docker run --shm-size=1gb -it --cap-add SYS_ADMIN --security-opt apparmor:unconfined --device=/dev/fuse --name neurodesktop -v ~/neurodesktop-storage:/neurodesktop-storage -p 8888:8888 --user=root vnmd/neurodesktop:xxxxxxx

**Comment by JonteP** [comment]
> On windows, this should work (not tested): docker run --shm-size=1gb -it --cap-add SYS_ADMIN --security-opt apparmor:unconfined --device=/dev/fuse --name neurodesktop -v ~/neurodesktop-storage:/neurodesktop-storage -p 8888:8888 --user=root vnmd/neurodesktop:xxxxxxx

Thank you @stebo85 !

I tried that earlier and again get "stuck" on "Ensuring /home/jovyan is owned by 1000:100 (chown options: -R)". Maybe this is just expected to take a while?

**Comment by stebo85** [comment]
Dear @JonteP - it shouldn't take one hour to start, Can you let us know what setup you are using? Are you running on Windows? Did you see any other errors? Can you reproduce the problem?

**Comment by JonteP** [comment]
@stebo85  I retried and it still took a very long time. However, when running the 20230525 build it started in an instant.

**Comment by JonteP** [comment]
Cool, I'll consider myself an early adopter then. :)

As an aside, now that neurodesktop is based on jupyterlab, I noticed that fsl behaves differently from my local install. In linux, I have installed fsl from their python script and it comes with it's own python environment allowing for e.g. integrating fsleyes in notebooks. However, the fsl in neurodesk seems to be installed differently, without this feature?

**Comment by stebo85** [comment]
the aim is that fsl behaves identically to before, but we indeed changed how we do this. can you give an example what's not working so we can fix this?

**Comment by stebo85** [comment]
Dear @JonteP,
You can use fslpython if you open the FSL container:
<img width="861" alt="image" src="https://github.com/NeuroDesk/neurodesktop/assets/4021595/65eba59f-950d-4ddd-8d34-90dd34031ab3">

However, do I understand correctly that you would like to run "import fsl" in a standard jupyter notebook outside of the FSL container? Do you have an example for this?

**Comment by JonteP** [comment]
Ah, I was running ml fsl. I wasn't aware that it was not equivalent. 
But yes, the motivation for me was to use it within notebooks. With example, do you mean an example of a case that is not covered by calling bash commands? My motivation was trying to run fsleyes as per this example: https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/fsleyes_notebook.html

Seems like there is a similar "issue" with mne that does not allow access from jupyter notebooks.

**Comment by stebo85** [comment]
ok, that example helps :) Let's see if we can get this to work!

**Comment by stebo85** [comment]
last item here moved to it's own issue
