### ISSUE TITLE
Neurodesktop daily build failing

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurodesktop#177]
Build terminates with:
The hosted runner: GitHub Actions 2 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

**Comment by stebo85** [comment]
is this still a problem?

**Comment by aswinnarayanan** [comment]
Yes, every couple of days the current builder just fails. 
For multiarch, we've switched to the official build-and-push action. We can see if that resolves the issue before looking into it further

**Comment by stebo85** [comment]
ok, makes sense :)

**Comment by aswinnarayanan** [comment]
Going to close this for now. Will re-open if error returns
