### ISSUE TITLE
Use github releases to create a new release

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#184]
The problem: Currently the release in Github doesn't reflect our actual release date.

Should we use the github release mechanism which then triggers the change on the website? Then Github / Website and App all are triggered with one release?

@aswinnarayanan, thoughts?

**Comment by aswinnarayanan** [comment]
Sounds good

**Comment by aswinnarayanan** [comment]
Do you think we should switch to versioning with separators for improved readability?

vnmd/neurodesktop:20230914    (current)
vnmd/neurodesktop:2023.09.14    (typical CalVer)
vnmd/neurodesktop:2023-09-14    (used by the jupyter notebooks)

Or is the current method is sufficient. What do you think?

**Comment by stebo85** [comment]
agree, that the more readable version would be nice! Should we go with jupyter notation?

**Comment by aswinnarayanan** [comment]
Sounds good
