### ISSUE TITLE
FSL GUI won't start

### ISSUE THREAD

**Issue by dkp** [NeuroDesk/neurodesktop#204]
Environment: Started neurodesktop on Binder

From the terminal, I can run command line tools like fslinfo.  I can also start fsleyes, but when I type `fsl`, the gui does not start, and instead complains:

fsl-6.0.7.4:~$ pwd
/home/jovyan
fsl-6.0.7.4:~$ fsl
Error in startup script: no such variable
    (read trace on "env(USER)")
    invoked from within
"set USER       $env(USER)"
    (file "/opt/fsl-6.0.7.4/tcl/fslstart.tcl" line 6)
    invoked from within
"source [ file dirname [ info script ] ]/fslstart.tcl"
    (file "/opt/fsl-6.0.7.4/tcl/fsl.tcl" line 71)
    invoked from within
"source ${FSLDIR}/tcl/${origname}.tcl"
    (file "/opt/fsl-6.0.7.4/bin/fsl" line 20)

Thank you,
Dianne

**Comment by stebo85** [comment]
Dear @dkp,

we can unfortunately not reproduce the problem:


![Image](https://github.com/NeuroDesk/neurodesktop/assets/4021595/6fe40ca1-18af-4379-b8b7-ce4a760fb948)

Could you describe in more detail how you are starting Neurodesk and how you start fsl?

**Comment by stebo85** [comment]
Dear @dkp,

Could you please provide more details on how you got this error and which Neurodesk link you used exactly? 

Thank you
Steffen

**Comment by dkp** [comment]
I went to play.neurodesk.org=>U.S.West.
If I select Neurodesktop=>RDP, then everything works fine.
However, if I select VNC, then I get this error: 

```fsl-6.0.7.4:~$ fsl
Error in startup script: no such variable
    (read trace on "env(USER)")
    invoked from within
"set USER       $env(USER)"
    (file "/opt/fsl-6.0.7.4/tcl/fslstart.tcl" line 6)
    invoked from within
"source [ file dirname [ info script ] ]/fslstart.tcl"
    (file "/opt/fsl-6.0.7.4/tcl/fsl.tcl" line 71)
    invoked from within
"source ${FSLDIR}/tcl/${origname}.tcl"
    (file "/opt/fsl-6.0.7.4/bin/fsl" line 20)
```

**Comment by stebo85** [comment]
Dear @dkp,

That's extremely helpful - thank you so much for finding this issue. We are looking into it.

@aswinnarayanan - any ideas?

Thank you
Steffen

**Comment by stebo85** [comment]
RDP: 
<img width="1312" alt="image" src="https://github.com/NeuroDesk/neurodesktop/assets/4021595/739dbf05-f938-4c62-8a88-1806e809384c">

VNC: 
<img width="634" alt="image" src="https://github.com/NeuroDesk/neurodesktop/assets/4021595/35d9468b-6ac6-412f-97a7-ca83507e726d">

**Comment by stebo85** [comment]
Dear @dkp,

We found the problem and it's fixed now. There will be a new release soon which includes this fix.

Thank you for finding and reporting it
Steffen

**Comment by dkp** [comment]
Cool!  Thank you!

**Comment by stebo85** [comment]
Dear @dkp,

Thank you again for reporting this problem. The new release is out now and the problem is fixed :)

Thank you
Steffen
