### ISSUE TITLE
Issue trying to run SPM from Matlab.

### ISSUE THREAD

**Issue by yoursurname** [NeuroDesk/neurodesktop#206]
There are many advantages to running the SPM GUI from matlab. 
I tried to use the method described here: https://www.neurodesk.org/tutorials-examples/tutorials/programming/matlab/
Like this: 
setenv("PATH",getenv("PATH") + ":/cvmfs/neurodesk.ardc.edu.au/containers/spm12_r7771_20230609”);
It can load FSL as in the example but not SPM.

When I run !spm12 I get the following message:
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
fl:filesystem:SystemError
spm12: Signal 121

**Comment by stebo85** [comment]
Dear @yoursurname 

you are trying to execute the compiled spm standalone version in matlab and that doesn't work of course!

if you want to run spm in matlab you need to download the matlab source code of SPM from their website and follow the SPM instructions to start the GUI in matlab. 

Let us know if that works for you
Kind regards 
Steffen

**Comment by stebo85** [comment]
Dear @yoursurname - is there any update on this? Did it work for you to install the source code of SPM and launch the GUI in matlab?
