### ISSUE TITLE
Installing neurodeskapp in an azure enclave

### ISSUE THREAD

**Issue by marcelzwiers** [NeuroDesk/neurodesktop#212]
Hi there,

I'm not sure if it is possible what I'm trying to accomplish, but here is the situation. I recently got involved in setting up some applications in a secure computing environment (https://andrea-cloud.com/). I set up a Ubuntu22 client that I can connect to with my web-browser (using Bastion -> rdp). The default XFCE environment is very basic and I have to whitelist all connectivity. I managed to install docker and the neurodeskapp, but when I try to launch the app I get:

![image](https://github.com/NeuroDesk/neurodesktop/assets/15156015/1b853d4a-6705-46e5-95ce-fff9c89732c7)

![image](https://github.com/NeuroDesk/neurodesktop/assets/15156015/96304661-4b38-4422-8a38-311975cccc8d)

(sorry for the png, I couldn't get clipboard transfer to work)

Any suggestions? Do you think it should be doable what I'm trying to do?

**Comment by stebo85** [comment]
In an Ubuntu 22 environment, I would suggest not using docker to run Neurodesktop but rather using the Neurocommand Linux install method (https://www.neurodesk.org/docs/getting-started/neurocommand/linux/) or CVMFS if that's possible in your secure environment (https://www.neurodesk.org/docs/getting-started/neurocontainers/cvmfs/)

The error in the neurodeskapp you see most likely comes from Docker not working correctly. If you want to continue following this path, then the first step would be testing, if you can actually run the plain docker command:
```
docker volume create neurodesk-home &&
sudo docker run \
  --shm-size=1gb -it --privileged --user=root --name neurodesktop \
  -v ~/neurodesktop-storage:/neurodesktop-storage \
  --mount source=neurodesk-home,target=/home/jovyan \
  -e NB_UID="$(id -u)" -e NB_GID="$(id -g)" \
  -p 8888:8888 \
  -e NEURODESKTOP_VERSION=2024-01-12 vnmd/neurodesktop:2024-01-12
```

Alternatively, you could try podman

**Comment by marcelzwiers** [comment]
Indeed, I cannot run that command:

![image](https://github.com/NeuroDesk/neurodesktop/assets/15156015/5cbc7a81-646a-40ea-9cc3-72399bee7105)

I really don't like this enclave tech :-(

I will go the neurocommand route (whenever I manage to get apptainer installed). Thanks for the help

**Comment by stebo85** [comment]
It looks like you don't have sudo privileges in this machine? Can you install anything via apt? If yes, apptainer should be easy to install:

```
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:apptainer/ppa
sudo apt-get update
sudo apt-get install -y apptainer 
```

Neurodesk should work in such enclave environments - we just need to figure out what's possible and what's not.

**Comment by marcelzwiers** [comment]
Wait, I added a sudo and fixed some typos, now I got a bit further:

![image](https://github.com/NeuroDesk/neurodesktop/assets/15156015/1530a4ae-d5cd-470b-95aa-2029daae4b5c)

**Comment by stebo85** [comment]
It seems to have trouble with
```
-e NB_UID="$(id -u)" -e NB_GID="$(id -g)" \
```
you can remove that for now. Later it would be good to figure out why there is no gid

**Comment by marcelzwiers** [comment]
I removed `-e NB_GID="$(id -g)"` and got:

![image](https://github.com/NeuroDesk/neurodesktop/assets/15156015/63df13b6-8416-44f3-82a8-4b1dbb80f53a)

**Comment by stebo85** [comment]
Yes, this now is CVMFS which probably doesn't have fuse mounting privileges.   So, I think your best bet is to install apptainer and go the HPC route.

**Comment by stebo85** [comment]
Can you try if this works? https://www.neurodesk.org/docs/getting-started/neurocontainers/cvmfs/ - maybe they didn't completely restrict fuse mounting. Otherwise, try a plain apptainer and download a container from here (https://www.neurodesk.org/docs/getting-started/neurocontainers/singularity/) to see if that route works

**Comment by marcelzwiers** [comment]
> Yes, this now is CVMFS which probably doesn't have fuse mounting privileges. So, I think your best bet is to install apptainer and go the HPC route.

Could it be that I need to whitelist a domain first?

**Comment by stebo85** [comment]
That should come at a later step, but you can try:

These are cvmfs domains we use
***@***.***@***@***.***@***@***.***@


Thank you

Steffen

--

W: https://mri.sbollmann.net<https://mri.sbollmann.net/>  | W: https://www.neurodesk.org<https://www.neurodesk.org/>  | T: https://twitter.com/sbollmann_MRI  | G: https://github.com/stebo85

Book meeting: https://calendly.com/s-bollmann/meeting

________________________________

**Comment by marcelzwiers** [comment]
Installing cvmfs fails, so I think I will try the neurocontainers (if I can get apptainer to install)
![image](https://github.com/NeuroDesk/neurodesktop/assets/15156015/8fe6700b-02a3-4609-b298-3bcbb2bdb69a)

**Comment by stebo85** [comment]
you can't whitelist that IP 11.5.0.4 so it could pull the CVMFS repo package? 

Is there a way we could get access to this environment so we can try a few things on our side?

**Comment by marcelzwiers** [comment]
Here's an update on things. I gave up on neurodesktop on Ubuntu and tries to get the environment-modules system installed. It failed to work normally (I had to manually source /etc/profile to get it to work, but it seemed unavailable in subshell, or at least neurocommand was giving errors about module commands not found). In our enclave there was also an old CentOS 7.9 system available, which I tried next. I started of with neurocommands and the good news is that I now got everything to work, just like that. I don't understand why people are so fond of Ubuntu

**Comment by marcelzwiers** [comment]
The neurodesktop gives users a nice menu structure to startup a terminal with pre-loaded module, are there other benefits about using this desktop instead of the default XFCE that comes with the CentOS VM?

**Comment by marcelzwiers** [comment]
I tested a few neurocommands that worked fine, but when I tried studio I got this error:

![image](https://github.com/NeuroDesk/neurodesktop/assets/15156015/e39cf09e-9eff-4374-bff0-02f65c895337)

**Comment by marcelzwiers** [comment]
FYI, if I re-install RStudio I get:

![image](https://github.com/NeuroDesk/neurodesktop/assets/15156015/1a5cbb61-a8d6-44ef-b9ad-3f50acc366f3)

**Comment by marcelzwiers** [comment]
Btw, I've seen this `module: command not found` also in Ubuntu. I think it's because I need to run the install script using `sudo`, which starts it's own (non-profile) shell. I even use `sudo -E env PATH=$PATH` (also to get the conda python environment working)

**Comment by marcelzwiers** [comment]
Ok, it gets even more weird. I went back to Ubuntu and manually sourced the module profile (somehow this seems the only way) and set the modulepath (using `module use`, somehow this also seems the only way), and then I managed to install the RStudio neurocontainer. And guess what the studio neurocommand just works

**Comment by marcelzwiers** [comment]
Yes, I'll send you a message on Mattermost@brainhack with details

**Comment by marcelzwiers** [comment]
In the meantime I made some more progress on Ubuntu, because I found out (somewhere in a Stackoverflow comment) that there is a `/usr/bin/add.modules` file that I could run. Now I finally got the module system to work and this in turn makes the rest a lot easier... :-)

**Comment by marcelzwiers** [comment]
Ok, I learned another important thing. I believe the module system under Ubuntu is not initializing properly because in Ubuntu `\bin\sh` is a dash shell, whereas in other distros it is bash

**Comment by stebo85** [comment]
@marcelzwiers, so this instruction here does not work? https://www.neurodesk.org/docs/getting-started/neurocontainers/cvmfs/#use-of-containers-in-the-module-system

**Comment by stebo85** [comment]
Another problem was that apptainer wasn’t running with user namespaces and the setuid was interfering with rrstudio
