### ISSUE TITLE
support multiple screens

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#24]
- using RDP native client?

**Comment by aswinnarayanan** [comment]
Instructions for connecting using RDP clients added https://github.com/NeuroDesk/neurodesk.github.io/commit/603480ff7808c45562937a20c2fcc1233a259a71

**Comment by stebo85** [comment]
awesome :) Works beautifully!

**Comment by air2310** [comment]
This works great! Thanks Aswin! It's going to make my data analysis so much easier :D

**Comment by VShawn** [comment]
FYI you can use a tool to open rdp quickly, it support multiple screens

https://github.com/VShawn/PRemoteM
