### ISSUE TITLE
set neurodesk.github.io as starting page in firefox

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#42]

**Comment by stebo85** [comment]
i saw the change - and will test in the release tomorrow

**Comment by aswinnarayanan** [comment]
Yup, it's working. But on its first run, Firefox opens a additional welcome page and privacy policy. Will try to remove those as well

**Comment by aswinnarayanan** [comment]
21346e5b95b0e96079050c095fd2239c35d3331c
