### ISSUE TITLE
I lost my permissions to the NeuroDesk repositories

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesktop#45]
Maybe something has changed with all the latest modifications. Can you please grant it back? (@civier)
Likewise, please also grant access to Dave White (@DavidjWhite33) and Will Woods (@willw1). Both of them need to add containers to neurocontainers.

Thanks,
Oren

**Comment by aswinnarayanan** [comment]
Hi @civier. DavidjWhite33 and willw1 have been added to neurocontainers.
Which repository did you want access to?

**Comment by stebo85** [comment]
@civier - instead of giving everyone access to everything we need to be more careful with permissions and grant them more granularly (mainly for security reasons since one wrong commit could by now cause considerable damage to the infrastructure we set up). The best and most secure option is to send pull request to the repositories that then get reviewed and approved - could you try if this workflow works for you?

**Comment by civier** [comment]
I want access to Neurocontainers as well. Regarding the other ones, I agree
that using pull requests is better.

Could you please coordinate with me the next time that you change
permissions? Today I was working, and got stuck in the middle.

Best,
Oren

--
Oren Civier
Neuroimaging Informatics Fellow
Swinburne Neuroimaging | National Imaging Facility
https://anif.org.au/team/oren-civier/
https://www.swinburne.edu.au/neuroimaging

Swinburne University of Technology
Hawthorn Campus, Advanced Technologies Centre, Room 914
+61 3 9214 4628 | +61 4 3101 6603
***@***.*** (Email/Teams video call)
https://twitter.com/orencivier

**Comment by aswinnarayanan** [comment]
@civier, the access rights were changed a few weeks ago 
have added you to neurocontainers now

**Comment by stebo85** [comment]
@civier - Pull requests would also work for Neurocontainers, but I agree that the risk of breaking things is low in this repository - so a direct access of the core team contributing is ok.

Regarding information of the next change: I informed everyone who contributed to the neurocontainers repository of the change, but you had not contributed anything yet, so you were not on the list:
![image](https://user-images.githubusercontent.com/4021595/134249738-834d2bc3-61e9-462f-97b1-7e44a0a8786e.png)
