### ISSUE TITLE
Very long pause when I start Neurodesktop on a NECTAR instance

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#56]
### Discussed in https://github.com/NeuroDesk/neurodesk.github.io/discussions/40

<div type='discussions-op-text'>

<sup>Originally posted by **civier** October 12, 2021</sup>
Hello,

When starting Neurodesktop on a NECTAR instance, it prints right on the start:
**usermod: no changes**
and then there is a very long pause (a few minutes) until it prints:
**=====**
**Starting SSH server**
*Starting OpenBSD Secure Shell server sshd
**======**
After that, it prints the rest of the stuff very quickly, until it is ready to use displaying:
**guacd[629]: INFO:	Listening on host 127.0.0.1, port 4822**

What is this pause about? Does it happen on all platforms? Notice that I experience the pause even when the vnmd/neurodesktop image is already downloaded into the NECTAR instance.

If this pause is an inevitable part of neurodesktop's stratup, I suggest to print a message such as "Loading. Please wait ..." before the pause. Otherwise, people may think something is stuck or not working (I thought so). 

Oren

P.S.
The exact command I use is:
sudo docker run   --shm-size=1gb -it --privileged --name neurodesktop   -v ~/neurodesktop-storage:/neurodesktop-storage   -e HOST_UID="$(id -u)" -e HOST_GID="$(id -g)"   -p 8080:8080 -h neurodesktop-20210929   vnmd/neurodesktop:20210929</div>

**Comment by aswinnarayanan** [comment]
Fixed 85c97be7d845a6430516a98e97f4a905e2180f54
