### ISSUE TITLE
Should we support and document the use of docker stop and start?

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#58]
This was discussed a bit in #57, but it's a separate issue:

Question 1: Is this a workflow we CAN support in terms of developer resources especially considering that Aswin and I have limited time and lots of other tasks that we need to work on based on the grant? So far no contributions to the core code have come from Sydney or Swinburne.

Question 2: If we start supporting this we need to make a few changes to the startup file and the documentation. Who implements these and maintains these changes?

Things that need to be adjusted:
 -a flag when running "docker start" to output errors.
- check if the cvmfs directory already exists before trying to recreate it (mkdir: cannot create directory ‘/cvmfs/neurodesk.ardc.edu.au’: File exists)
- documenting this use consistently
- anything else that we need to be aware of?

**Comment by TomEmotion** [comment]
Thanks Steffen. Makes sense to assess i) the need and ii) exactly what resources we have to implement & maintain (i.e. who). We'll chat with this today @Swinburne.
