### ISSUE TITLE
Lower privilege using --cap-add=SYS_ADMIN when starting neurodesktop

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurodesktop#59]
--cap-add=SYS_ADMIN might provide sufficient permissions for running internal singularity container versus using the full --privileged mode.
Need to test and see if anything breaks

Ref: https://groups.google.com/a/lbl.gov/g/singularity/c/e9mlDuzKowc/m/Kx-aP_vkEgAJ

**Comment by aswinnarayanan** [comment]
Thanks @civier, would you be able to try this in place of --priveleged on neurodesktop and test the behaviour?

**Comment by stebo85** [comment]
closed as dealing with this in #55

**Comment by civier** [comment]
> Thanks @civier, would you be able to try this in place of --priveleged on neurodesktop and test the behaviour?

Sorry I missed it. Was quite busy lately.
Is it still relevant for #55? I can ask the SNI fellows to test it, now that we all use Neurodesktop.

Best,
Oren

**Comment by stebo85** [comment]
no more input needed right now @civier

**Comment by aswinnarayanan** [comment]
Continuing the reduced permission discussion from #55 

Hi @civier. We're testing out running neurodesktop with reduced permissions.
Would you (and the group) be able to test out this quickstart script for neurodesktop

```
sudo docker run \
  --shm-size=1gb -it --cap-add SYS_ADMIN \
  --security-opt apparmor:unconfined --device=/dev/fuse \
  --name neurodesktop \
  -v ~/neurodesktop-storage:/neurodesktop-storage \
  -e HOST_UID="$(id -u)" -e HOST_GID="$(id -g)" \
  -p 8080:8080 -h neurodesktop-20211028 \
  vnmd/neurodesktop:20211028
```

Let us know if anything doesn't work like it used to

**Comment by aswinnarayanan** [comment]
@civier Any feedback using the updated run command?

**Comment by civier** [comment]
@DavidjWhite33 @TomEmotion @willw1 @Matte16  @PJLYONS
SNIers, I tag you here, so you know where to report issues with the new arguments to run neurodesktop.
If all seems to work fine with the new arguments, please report as well.
Cheers,
Oren

**Comment by stebo85** [comment]
seems to be working since a while. Closing for now.

**Comment by Matte16** [comment]
Hi Steffan,

yes - thanks!

Sorry, i have not revisited that data since then but will be soon.

Thankyou very much,

Matt.

________________________________
