### ISSUE TITLE
Add to Neurodesktop a tool to analyse disk space (e.g., Filelight)

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesktop#62]
Hi all,

In order to give users a full GUI experience, I would like to include a graphical disk storage analyser. I would go for Filelight (https://en.wikipedia.org/wiki/Filelight), as it is easy to install (apt-get install) and also displays the number of files in each directory shown in the pie chart. Number of i-inodes is often an issue for users that sshfs-mount or sync with storage on HPCs. Do you have better options? (one shortcoming of Filelight is that the sizes of the pieces in the pie chart is still according to the volume of each directory, rather than total number of files. I'd prefer a tool where the size can reflect either of the two)

@stebo85 @aswinnarayanan Can I add stuff to Neurodesktop myself, or do you want to take care of it yourself? If you want other to contribute, could we arrange as part of one of the workshops some tutorial about how it is set up? Where in the recipe code should be added, and what are the development policies? (forking, separate pull requests, versioning, testing procedures, etc.)

Lastly -- can you please let everybody in the project set assignees/labels/projects/etc. to issues in all of the repositories? Right now I do not have permissions to do it in Neurodesk/neurodesktop, for example.

Best,
Oren

**Comment by civier** [comment]
Noticed it is already added

**Comment by civier** [comment]
Re-opening because I noticed that filelight is in my Accessories menu because I installed it, not because it comes with Neurodesktop. That is so cool that apt-get actually adds the apps to the menu -- I love it!

@stebo85 @aswinnarayanan  In any case, please check my original post above, and let me know what you think.

**Comment by aswinnarayanan** [comment]
@civier How large was the filelight install on the existing neurodesktop?

**Comment by civier** [comment]
It installs many libraries, so I'm not sure.
What is the best way to quantify it?

**Comment by aswinnarayanan** [comment]
Ah yes, when you install it with apt-get, how much space does it request? Including the libraries

**Comment by civier** [comment]
When it asks me if to continue, apt-get writes:
"After this operation, 82.6 MB of additional disk space will be used."

Oren

**Comment by civier** [comment]
If it's a question of diskspace, we can put all utilities that do not
strictly need to be in the main docker into a separate misc container. Do
we already have such a container?
(The only question is how to maintain such a container effectively by
several people, given that we currently edit the neurocontainers gihub
directly)

Best,
Oren


--
Oren Civier
Neuroimaging Informatics Fellow
Swinburne Neuroimaging | National Imaging Facility
https://anif.org.au/team/oren-civier/
https://www.swinburne.edu.au/neuroimaging

Swinburne University of Technology
Hawthorn Campus, Advanced Technologies Centre, Room 914
+61 3 9214 4628 | +61 4 3101 6603
***@***.*** (Email/Teams video call)
https://twitter.com/orencivier

**Comment by aswinnarayanan** [comment]
I think the best option would be to create filelight neurocontainer. Then we let the container delivery and menu system take care of the rest. It'll help keep out core image as small as possible.

**Comment by aswinnarayanan** [comment]
> @stebo85 @aswinnarayanan Can I add stuff to Neurodesktop myself, or do you want to take care of it yourself? If you want other to contribute, could we arrange as part of one of the workshops some tutorial about how it is set up? Where in the recipe code should be added, and what are the development policies? (forking, separate pull requests, versioning, testing procedures, etc.)

Thanks for raising this. Happy to accept help on neurodesktop. Neurodesktop development should focus on the core development and functionality, and we have all of these open [issues](https://github.com/NeuroDesk/neurodesktop/issues). 
Just wanted to note, that we should aim to put minimum packages onto neurodesktop as possible (we should be slimming the existing one down actually). Best option for neurodesktop contributions would be fork + pull_request. If someone is looking at developing on the neurodesktop core or working on one of the existing issues, happy to arrange some time or workshop to discuss things.

**Comment by aswinnarayanan** [comment]
>Lastly -- can you please let everybody in the project set assignees/labels/projects/etc. to issues in all of the repositories? Right now I do not have permissions to do it in Neurodesk/neurodesktop, for example.

Can I get further information. What is the permissions needed for?

**Comment by civier** [comment]
Don't have time to work on it right now. Not urgent.
@stebo85  Can you please let me permission to change labels (in all the issue forums) so I can mark it as "not to be done right now" and you won't need to monitor it.

**Comment by stebo85** [comment]
Dear @civier - no, labels are managed by Aswin and me.

**Comment by Akshaiy91** [comment]
@civier I found an application called QDirStat that I believe fulfils this functionality and its only 2MB. I'll put a pull request through.

**Comment by aswinnarayanan** [comment]
Thanks @Akshaiy91. Closing

**Comment by civier** [comment]
Thanksa lot @Akshaiy91 
BTW, I don't know how you are. Do you mind adding your details to your Github profile?
Thanks ahead, Oren

**Comment by stebo85** [comment]
Dear @civier - you don't need to know who contributors are - please respect if contributors don't put their full name on their github profile - there are many good reasons for doing so.

**Comment by civier** [comment]
@stebo85 You are totally right. I didn't think of that :-(

@Akshaiy91 I take my words back. No need to share your identity unless you wish to.

**Comment by Akshaiy91** [comment]
NP Stefan and Oren, I was anyway intending on updating my Github profile sometime and I'll add the details I wish to then.
