### ISSUE TITLE
Docker named volume for persistent storage 

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurodesktop#63]
https://docs.docker.com/storage/volumes/

Docker named volume (over bind mount) may be an option for persistent home directory or local installs.

This could solve the performance issues with bind mounts which are more useful when host os needs to access the shared files.

**Comment by stebo85** [comment]
Great idea :)

**Comment by stebo85** [comment]
@aswinnarayanan - is this still relevant?

**Comment by stebo85** [comment]
completed. We use named volumes now for persistent home storage.
