### ISSUE TITLE
integrate neurodesk in nectar

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#65]
nectar has applications like jupyter and we could add neurodesktop to this list?

**Comment by civier** [comment]
I thought I already discussed with you the NECTAR integration before, and
you told me that you are on the case.
Have you already discussed it with them? I think it should be evaluated in
light of the virtual desktop that NECTAR are planning to provide themselves
-- I already spoke with the people who work on that, so I'll try to find
our conversation and forward to you.

**Comment by stebo85** [comment]
https://desktop.rc.nectar.org.au/home/
