### ISSUE TITLE
Stable version?

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurodesktop#77]
Release stable version of NeuroDesktop to incorporate into startup scripts/applications.

Applications (.exe, .command, .run) will be version controlled by release for reproducibility and hard coded by docker image date

Applications can be uploaded to website for download?
@stebo85

**Comment by aswinnarayanan** [comment]
Latest stable version is available at this link https://github.com/NeuroDesk/neurodesk.github.io/blob/hugo-docsy/data/neurodesktop.toml

The website pulls from this value as well.

**Comment by thomshaw92** [comment]
Great - I will hard code yesterdays version as the 1st release for the application :)
Need to chat about if these apps can go on the website for download too.

**Comment by stebo85** [comment]
yes, should be straight forward to link to the applications from the website?

**Comment by thomshaw92** [comment]
> yes, should be straight forward to link to the applications from the website?

I don't think I have the know-how for this. @aswinnarayanan ?

**Comment by stebo85** [comment]
I think a link to https://github.com/NeuroDesk/neurodesktop/raw/main/Windows_run_Neurodesk/NeuroDesktop.exe would probably be enough? In addition you could build this exe file automatically using github actions?

And one more problem that need to get by:
![image](https://user-images.githubusercontent.com/4021595/145153464-12ce7036-ad2f-4a3b-b5ff-2735b33f46b9.png)

**Comment by aswinnarayanan** [comment]
Hi @thomshaw92, the application links have been added now.

**Comment by stebo85** [comment]
Dear @thomshaw92 - the windows starter script works well for people :) One little feedback: It starts firefox if this is the default browser, but firefox doesn't play well with neurodesktop on some computers - can you check for that and output a warning :?

**Comment by stebo85** [comment]
@thomshaw92 - did you have a chance to look at this default browser issue? Firefox doesn't work on some computers with neurodesk - see issue #70

**Comment by Akshaiy91** [comment]
I've found a solution for this. Just need to amend a few things. Will test and send a pull request soon.

**Comment by aswinnarayanan** [comment]
Thanks @Akshaiy91, an excellent addition.

@stebo85, should we explicitly call out firefox as being unsupported?

Current message is  `Google Chrome or Microsoft Edge Browser is recommended for use with Neurodesktop. Other browsers may work. Please try Chrome or Edge if running into issues.`

**Comment by stebo85** [comment]
This message is good :) Firefox works, but sometimes doesn't and we haven't figured out why. Could it be that the browser detection breaks the startup script @Akshaiy91 - for me it gets stuck now in an infinite loop?

**Comment by aswinnarayanan** [comment]
@stebo85, the latest code loops for me too. But @Akshaiy91's pull request version seems to work.

**Comment by stebo85** [comment]
Ahh! The update of guacamole changed it ... great find! Thank you for fixing this! Sorry for suspecting the browser check first ... I didn't even think that the updated version could have done that.

**Comment by thomshaw92** [comment]
Not a huge issue - but the new .exe downloads the latest Docker version, not the stable release on Windows. 
Should we be making sure it runs only stable releases?

**Comment by stebo85** [comment]
@thomshaw92 - yes, I couldn't get it to work to extract the latest version from the web (windows lacks webrequests by default)
