### ISSUE TITLE
Update to fmriprep

### ISSUE THREAD

**Issue by YohanWards** [NeuroDesk/neurodesktop#79]
Please update to 20.2.6

**Comment by stebo85** [comment]
Hi @YohanWards 

fmriprep/20.2.6 is now available in the latest version of neurodesk 20211210 as container fmriprep_20.2.6_20211209

can you test and let me know if it all works as expected?

Kind regards
Steffen

**Comment by stebo85** [comment]
@YohanWards - did you check if this worked for you so I can close this issue?

**Comment by YohanWards** [comment]
Sorry Steffen I'm on holiday at the moment and don't have great internet
access. Thanks for adding the latest version, I'll have a go at running it
in the new year.

**Comment by stebo85** [comment]
@YohanWards - did you have a chance of testing this, so I can close this issue?

**Comment by YohanWards** [comment]
Hi Steffen, sorry for the delay in testing this, it appears to be running
perfectly fine so far. I will know in a few hours if the outputs are
sensible but from experience once it successfully builds the workflow and
begins the image preprocessing I have rarely encountered any issues. Thanks
again for updating it!

**Comment by YohanWards** [comment]
Can confirm, preprocessing was completed without errors using the 20.2.6 version

**Comment by stebo85** [comment]
Awesome, thank you for confirming @YohanWards :)
