### ISSUE TITLE
When connecting with RDP via web browser FROM UBUNTU, copy and paste works only one way

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesktop#81]
When connecting from Linux, I can copy things from Neurodesktop outside to the Linux desktop hosting the web browser, but not vise versa.
It is not about the key combination, as I also tried through the menu.
I believe it is not about the specific application I copy from/to, as I tried both Firefox and the terminal.
I believe it is not about a specific version of Ubuntu, as I tried both from a desktop running an old version of kubuntu, and from the new NECTAR Desktop (the test version).
I believe it is not about the client web browser, as I tried both Firefox and Chrome.
Any clue what is the problem and how to fix it?

**Comment by stebo85** [comment]
sounds like a security feature? have you enabled clipboard access in your browsers?

**Comment by civier** [comment]
Thanks @stebo85 
Following your lead, I browsed in Firefox to about:config, searched for all the flags with 'clipboard' in their name, and changed the 'false' ones to 'true' (these are the bold ones below)
<img width="1680" alt="Screen Shot 2022-01-10 at 8 43 33 pm" src="https://user-images.githubusercontent.com/8280611/148749721-39e040e9-740c-4bae-af04-500bcbd600e4.png">
Now copy and paste into Neurodesktop works!
**Any clue which of the flags (or combination of them) makes the difference?**

With regard to Chrome, when you connect the first time it asks you if you want Chrome to see the clipboard, so users need to choose "yes". To bring this question again, Chrome settings need to be restored to default.  **Do you know what should be changed exactly so restore to default settings won't be necessary?** Some people would not like to erase their settings.

**Comment by stebo85** [comment]
Dear @civier 

Thank you for testing this out and finding a solution :)

I don't know which falgs need to be on, but you could test this quickly, right? My guess would be dom.events.asyncClipboard.read

Chrome and edge have a little icon next to the favorite button in the URL bar that allows changing the settings: 
![image](https://user-images.githubusercontent.com/4021595/148859904-b0616a4a-76b3-47ef-9f14-5deb7cb15285.png)

Can you document this on the website? e.g. here: https://neurodesk.github.io/docs/neurodesktop/troubleshooting/

Kind regards
Steffen

**Comment by civier** [comment]
It is dom.events.testing.asyncClipboard flag in Firefox that needs to be enabled:
https://bugzilla.mozilla.org/show_bug.cgi?id=1610209
I'll add it to the docs.

**Comment by civier** [comment]
@thomshaw92 Any way to turn on dom.events.testing.asyncClipboard fron the start-up script for Linux? Can Firefox flags be changed from the command line? (no clue)

**Comment by stebo85** [comment]
@civier - did you document the dom.events.testing.ascyncClipboard flag as you proposed?

**Comment by stebo85** [comment]
@civier - can you please let me know if you documented this or not, so I can close this issue?

**Comment by stebo85** [comment]
@civier - any updates on this from your side?

**Comment by stebo85** [comment]
@civier - no action required anymore from your side (although it would have been nice to see a contribution from you)
