### ISSUE TITLE
Should be disable authentication in guacamole?

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#85]
https://guacamole.apache.org/doc/gug/configuring-guacamole.html?highlight=disable%20authentication#authentication-and-security

there seems to be a disable auth setting:

disable-auth
If set to “true”, authentication will be disabled. Note that this refers to authentication that takes place while connecting. Any authentication enforced by the server over the remote desktop session (such as a login dialog) will still take place. By default, authentication is enabled and only used when requested by the server.

If you are using NLA, authentication must be enabled by definition.

**Comment by aswinnarayanan** [comment]
Hi @stebo85, thanks for the link, I was looking into this yesterday.

If I understand this correctly, the guacamole login is automatically authenticating us past the server's rdp authentication as well, and this "disable-auth" controls something about that passthrough process. Even if we disable guac login some other way (which doesn't seem be easy or possible), we'll also have to turn off the authentication by the xrdp server somehow.
The advantage of the guacamole client is it provides us with the convenient api for authenticating via the url (?username=user&password=password)

Most significantly, the guacamole docs strongly recommends not disabling the Guacamole authentication
https://guacamole.apache.org/faq/#disable-auth 

![image](https://user-images.githubusercontent.com/25297584/151905083-ad1f8823-74e0-4a46-a118-e7d4961c33e5.png)

For the mybinder issue, its probably recommended (and more secure) trying to passthrough the username/password via the guacamole api like we do for the desktop version

**Comment by stebo85** [comment]
ok, makes sense! Then we need to figure out why the desktop is not loading when passing the username and password via the URL. 

This opens the desktop, but asks for username and password, once entering them it is stuck:
http://192.9.172.90/v2/gh/NeuroDesk/jupyter-remote-desktop-proxy/k8s?urlpath=neurodesktop

This doesn't work either:
http://192.9.172.90/v2/gh/NeuroDesk/jupyter-remote-desktop-proxy/k8s?urlpath=neurodesktop/#/?username=jovyan&password=password

What am i missing :?

**Comment by aswinnarayanan** [comment]
Yeah, the main link isn't working for me right now either. There might be some issues with the kube server, I'll take a look.

For authentication via url, I'm still investigating. 

This seems to be due to binder. The url seems to work on jupyterhub. But binder is using a token authentication process to launch the jupyterhub instance and this is stripping the auth url

**Comment by aswinnarayanan** [comment]
Resolved

**Comment by stebo85** [comment]
yes, fantastic fix!!!!
