### ISSUE TITLE
Optimal memory allocation for users experiencing memory problem in Windows?

### ISSUE THREAD

**Issue by neuro-sevas** [NeuroDesk/neurodesktop#87]
I'm working on an FAQ for the memory problem in Windows, and I'm wondering if anyone has any advice on what the optimal memory allocation would be to suggest to users?

**Comment by stebo85** [comment]
Dear @neuro-sevas,

Thank you - this will be super helpful :)

The memory requirements depend on the data and tools the users want to use. To help with this I added a little memory monitor in the application bar and this will tell users how much memory they have and how much they consumed. If you have a look at neurodesktop:20220208 this should already be there and documenting this feature would be great.

It would also be helpful to document for windows users that don't use WSL2 how to check how much memory they provide to the docker container in the docker settings :)

Thank you for your help!
Cheers
Steffen

**Comment by neuro-sevas** [comment]
Hi @stebo85 

Thanks so much for your reply :)

Thank you for adding that function! Given that different processing tools and data will require different amounts of memory, I might suggest that users check how much is being used, and adjust accordingly until they find the right amount.

Happy to document this feature - where would it be most helpful for this to be? In this FAQ or in a separate spot?

I'll add a section in this FAQ for users who don't use WSL2 too.

Always happy to help where I can!

Cheers,
Steff

**Comment by civier** [comment]
Great work @neuro-sevas 

For MRtrix's FBA analysis, 32GB RAM is often necessary (see point 21):
https://mrtrix.readthedocs.io/en/3.0.3/fixel_based_analysis/mt_fibre_density_cross-section.html?highlight=ram

So if people do not really have a limit (they run on a machine with a lot of memory), you can specify that 32GB can be ideal.

**Comment by neuro-sevas** [comment]
Thanks @civier!

I'll suggest 32GB to start with and suggest users adjust this based on their needs.

**Comment by stebo85** [comment]
Dear @neuro-sevas ,

Adding it here would be good I think: https://neurodesk.github.io/docs/neurodesktop/troubleshooting/ - what do you think?

Cheers
Steffen

**Comment by stebo85** [comment]
completed. Thank you for contributions :)
