### ISSUE TITLE
Why NeuroDesktop.run is a self-extracting archive?

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesktop#91]
@thomshaw92 I want to make changes in https://github.com/NeuroDesk/neurodesktop/raw/main/Linux_run_Neurodesk/NeuroDesktop.run
and I see that it's a self-extracting archive.
Can you explain me why it's necessary if there is only a single script inside? Am I missing something?
(sorry if it's a stupid question)

**Comment by stebo85** [comment]
Dear @civier,

The script file to build NeuroDesktop.run is here
https://github.com/NeuroDesk/neurodesktop/tree/main/Linux_run_Neurodesk/Start_NeuroDesktop_script_files

and the instructions are in the accompanying Readme: 
https://github.com/NeuroDesk/neurodesktop/blob/main/Linux_run_Neurodesk/Start_NeuroDesktop_script_files/README.md

**Comment by stebo85** [comment]
If you change the .sh file make sure to build the run again. I think @thomshaw92 idea was that the run file is independent of bash and doesn't require it.

**Comment by civier** [comment]
@thomshaw92 Is that really the case? Did you simply want it to run also if people don't have bash installed or are there other consideration to use .run?
(we are still academics after all, and I want to learn :-)

@stebo85 I unfortunately don't have time to do the changes right now, so you can close this issue after @thomshaw92 replies
@thomshaw92 if you have time to dedicate to it, I can tell you what are the problems I discovered (I don't think many people will have them, so it's not urgent)

**Comment by thomshaw92** [comment]
My idea was that a self extracting archive is a 'double click' option that works on all flavours of linux. As opposed to a bash script that is more tricky and doesn't always work.
Instructions are in the README - I will have time to look at this again after 1 March. :) 

The things that need to be implemented are the Firefox check, mounting drives, and downloading the latest stable version.

**Comment by civier** [comment]
@thomshaw92 Why bash script not always work? Is it because some flavours don't have bash installed?
Regarding the double click -- is it that some desktop interfaces only allow you to execute .run but not .sh? I'm not sure that I get it.

**Comment by civier** [comment]
@aswinnarayanan It is related to a chat I had with @stebo85 (commitment to work on issues). I will bring it up in the next AEDAPT meeting so everybody can be up to date.

**Comment by aswinnarayanan** [comment]
Hi @civier, I mean this issue isn't about the contribution itself. So questions and follow-up questions are about benefits of .run vs bash.
What is the issues you are having with the .run executable?

**Comment by civier** [comment]
@aswinnarayanan I will work on it myself when I find the time in the future. It's not urgent, and I know that you're very busy in UQ. Cheers, Oren

**Comment by aswinnarayanan** [comment]
Okay @civier. Cheers
