### ISSUE TITLE
neurodesktop does not work in podman

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#95]
guacamole crashes on startup when using podman instead of docker. Everything seems to be fine, except the start of guacd:

in docker it would be:
```
guacd[203]: INFO:       Listening on host 127.0.0.1, port 4822
```

in podman this happens:
```
guacd[199]: INFO:       Listening on host ::1, port 4822
```

I think this could be the problem, but I am now trying to debug with 
```
su user -c "guacd -f -L debug && echo"
```

**Comment by aswinnarayanan** [comment]
This is probably configured by /etc/guacamole/guacamole.properties

https://guacamole.apache.org/doc/gug/configuring-guacamole.html?highlight=ipv6#guacamole-properties

**Comment by aswinnarayanan** [comment]
guacd-hostname defaults to localhost
guacd-port defaults to 4822

We may need to override these using startup.sh if using ipv6

**Comment by stebo85** [comment]
starting guacd with -b 127.0.0.1 solves the problem. I wasn't able to fix it with guacamole-properties

**Comment by aswinnarayanan** [comment]
Nice find 👍
