### ISSUE TITLE
Rsync and spinal cord toolbox

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurodesktop#99]
Scripts in SCT create rsync processes (rsync not in the container.)
Will fix

**Comment by stebo85** [comment]
ok, rebuilding :) https://github.com/NeuroDesk/neurocontainers/runs/6071285738?check_suite_focus=true

**Comment by stebo85** [comment]
done and released in [20220419](https://hub.docker.com/layers/neurodesktop/vnmd/neurodesktop/20220419/images/sha256-58eb51c1f34555c0762731f809f338ce6415f7fac9606ee4271ed549f2054019?context=explore)
